# training config for fedbuff on cifar10
batch_size: 16
test_batch_size: 1000

model_name: "resnet18"
in_channels: 3
num_classes: 10
img_size: 32

sync: false
lamda: 0.005

fedbuff:
  k: 10

