# training config for fedasync on fashionmnist
batch_size: 64
test_batch_size: 1000

model_name: "cnn4"
in_channels: 1
num_classes: 10
img_size: 28

sync: false
lamda: 0.005

fedasync:
  strategy: "constant"
  alpha: 0.6
  a: 0.5
